name: bertopic_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - tqdm
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - langdetect
  - nltk
  - umap-learn
  - hdbscan
  - gensim
  - spacy
  - sentence-transformers
  - typing-extensions
  - pip
  - pip:
    - bertopic==0.17.0
    - octis==1.14.0
    - scikit-optimize==0.10.2
    - transformers==4.51.3
    - tokenizers==0.21.1
    - tomotopy==0.13.0
    - unidecode==1.4.0
    - plotly==6.0.1
    - huggingface-hub==0.30.2
    - flask==3.1.0
    - pyyaml==6.0.2
    - regex
